# Generated by Django 5.2.1 on 2025-05-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_customerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='pickup_location',
            new_name='department',
        ),
    ]
