# Generated by Django 3.2.25 on 2025-05-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung')], max_length=20)),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B')], max_length=1)),
                ('storage_gb', models.PositiveIntegerField()),
                ('camera_megapixels', models.DecimalField(decimal_places=1, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
