# Generated by Django 3.2.25 on 2025-05-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storage_gb',
            field=models.PositiveIntegerField(help_text='Enter storage in GB as an integer (e.g. 128)'),
        ),
    ]
