# Generated by Django 5.2.1 on 2025-05-17 16:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/demo/image/upload/sample.jpg', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
